Tea-Bliss/BE_Tea_Bliss

build.gradle, src/main/java/store/teabliss/common/security/SecurityConfig.java, src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/dto/MemberSignUpDto.java, src/main/java/store/teabliss/member/entity/Member.java, src/main/java/store/teabliss/member/mapper/MemberMapper.java, src/main/java/store/teabliss/member/service/MemberService.java, src/main/resources/application.yml, src/main/resources/mapper/MemberMapper.xml
회원가입 로컬 테스트 성공
Init 파일로 추가 및 수정 완료
=> [feat] 회원가입 기능 Init 추가

src/main/java/store/teabliss/member/controller/MemberController.java
=> dev 브랜치 init용 파일 수정

src/main/java/store/teabliss/common/response/CommonResponse.java, src/main/java/store/teabliss/common/response/ErrorResponse.java, src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/dto/MemberResponse.java, src/main/java/store/teabliss/member/exception/DuplicationMemberEmailException.java, src/main/java/store/teabliss/member/exception/DuplicationNicknameException.java, src/main/java/store/teabliss/member/exception/MemberException.java, src/main/java/store/teabliss/member/exception/MemberExceptionHandler.java, src/main/java/store/teabliss/member/exception/MemberStatus.java, src/main/java/store/teabliss/member/exception/NotFoundMemberByEmailException.java, src/main/java/store/teabliss/member/exception/NotFoundMemberByIdException.java, src/main/java/store/teabliss/member/mapper/MemberMapper.java, src/main/java/store/teabliss/member/service/MemberService.java, src/main/resources/mapper/MemberMapper.xml
feat/member -> dev
- 회원가입 시 존재하는 이메일 검색용, 단일 회원 이메일 검색 추가
- 회원 커스텀 Exception Init(중복 이메일 등 4가지)
=> [feat] 단일 회원 이메일 검색 추가, 회원 커스텀 Exception Init

src/main/java/store/teabliss/common/security/JsonUsernamePasswordAuthenticationFilter.java, src/main/java/store/teabliss/common/security/JwtAuthenticationProcessingFilter.java, src/main/java/store/teabliss/common/security/JwtService.java, src/main/java/store/teabliss/common/security/JwtServiceImpl.java, src/main/java/store/teabliss/common/security/LoginFailureHandler.java, src/main/java/store/teabliss/common/security/LoginSuccessJWTProvideHandler.java, src/main/java/store/teabliss/common/security/SecurityConfig.java, src/main/java/store/teabliss/common/security/UserDetailsServiceImpl.java
- [✅] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
feat/login->main
로그인 ,jwt provider를 장착했으나 뭔 오류인지 모르겠습니다 ㅜㅜ
=> ✨feat:로그인 기능 추가(오류발생 ㅜㅜ)

src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/mapper/MemberMapper.java, src/main/java/store/teabliss/member/service/MemberService.java, src/main/resources/mapper/MemberMapper.xml
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 회원 기본적인 CRUD 추가
- member ID값을 Long 타입으로 변경으로 인한 수정 작업
- 정상 확인
=> [feat] 회원 기본 CRUD 생성, member ID Long 타입 변경으로 인한 수정

src/main/resources/mapper/MemberMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 에러 수정
=> [fix] Delete 네이밍 에러 수정

src/main/resources/mapper/MemberMapper.xml
- [] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [✅] 버그 수정
dev->main
sql 구문 에러고쳤습니다!
정상작동!
=> 🐛fix:sql syntax 에러 수정

build.gradle, src/main/java/store/teabliss/common/security/JwtService.java, src/main/java/store/teabliss/common/security/SignInSuccessHandler.java, src/main/java/store/teabliss/common/security/UsernamePasswordAuthenticationFilter.java, src/main/resources/application.yml, src/main/resources/mapper/MemberMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
feat/login -> dev
- 자체 로그인 성공 확인을 위한 수정 작업
- JWT Secret 키 환경변수화
- 로그인 성공 시 헤더에 AccessToken과 RefreshToken 발행함을 확인
- 로그인 실패 시 '회원 아이디와 일치한 정보가 없습니다.' 로 메시지를 확인.
=> [feat] 로그인 경로 수정 및 JWT SECRET 변수화

src/main/java/store/teabliss/common/config/SecurityConfig.java, src/main/java/store/teabliss/common/security/signin/JwtAuthorizationFilter.java, src/main/java/store/teabliss/common/security/signin/UsernamePasswordAuthenticationFilter.java, src/main/java/store/teabliss/common/security/signin/handler/SignInFailureHandler.java, src/main/java/store/teabliss/common/security/signin/handler/SignInSuccessHandler.java, src/main/java/store/teabliss/common/security/signin/service/JwtService.java, src/main/java/store/teabliss/common/security/signin/service/UserDetailsServiceImpl.java
- [] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- [v] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- feat/login -> dev
- OAuth2 서비스 추가를 위한 서비스 패키지 분리 처리
=> [rename] OAuth2 적용을 위한 패키지 분리

src/main/java/store/teabliss/common/config/SecurityConfig.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/login -> dev
- SecurityConfig.java에서 OAuth2 테스트를 위한 관련 코드 전부 주석 처리
=> [fix] OAuth2 테스트 코드 주석 처리

src/main/java/store/teabliss/common/security/signin/handler/SignInSuccessHandler.java, src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/dto/MemberSignInDto.java, src/main/java/store/teabliss/member/dto/MemberSignUpDto.java, src/main/java/store/teabliss/member/entity/MemberRole.java, src/main/java/store/teabliss/member/entity/typehandler/MemberRoleTypeHandler.java, src/main/java/store/teabliss/member/mapper/MemberMapper.java
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
feat/login -> dev
- 로그인 스웨거 추가
- 해당하는 로그인 Dto 추가
- 로그인 성공시 반환 데이터 수정
- 현재 JSON으로 반환하도록 설정
- 예시)
"status": 200,
"message": "Success",
"data": {
"memId": 8
}
=> [feat] 로그인 스웨거 추가, 반환 MemberResponse로 변경 작업

src/main/java/store/teabliss/common/config/WebConfig.java
- [✅] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
cors 에러 해결하기 위해 임시로 일단 전역적으로 config 설정하였습니다
=> ✨feat:cors 에러 안나게 하기위해 전역cors confing 추가

src/main/java/store/teabliss/member/dto/MemberSignUpDto.java, src/main/java/store/teabliss/member/exception/MemberStatus.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/login -> dev
- 중복 체크 메시지 수정
- 회원가입 DTO Valid 수정
=> [fix] 중복 에러 메시지 수정, 회원가입 Valid 수정

src/main/java/store/teabliss/common/config/SecurityConfig.java
- [] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [✅] 버그 수정
feat/tea->main
=> 🐛fix: cors 전역적으로 설정하기위해 시큐리티 수정

src/main/java/store/teabliss/common/config/WebConfig.java, src/main/java/store/teabliss/common/security/signin/handler/SignInSuccessHandler.java
- [✅] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
=> feat: 로그인할시 쿠키 추가!

src/main/java/store/teabliss/common/config/RestTemplateConfig.java, src/main/java/store/teabliss/common/config/SecurityConfig.java, src/main/java/store/teabliss/common/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/store/teabliss/common/security/oauth2/exception/OAuth2AuthenticationProcessingException.java, src/main/java/store/teabliss/common/security/oauth2/handler/OAuth2AuthenticationFailureHandler.java, src/main/java/store/teabliss/common/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/store/teabliss/common/security/oauth2/service/CustomOAuth2UserService.java, src/main/java/store/teabliss/common/security/oauth2/service/OAuth2UserPrincipal.java, src/main/java/store/teabliss/common/security/oauth2/user/GoogleOAuth2UserInfo.java, src/main/java/store/teabliss/common/security/oauth2/user/GoogleOAuth2UserUnlink.java, src/main/java/store/teabliss/common/security/oauth2/user/OAuth2Provider.java, src/main/java/store/teabliss/common/security/oauth2/user/OAuth2UserInfo.java, src/main/java/store/teabliss/common/security/oauth2/user/OAuth2UserInfoFactory.java, src/main/java/store/teabliss/common/security/oauth2/user/OAuth2UserUnlink.java, src/main/java/store/teabliss/common/security/oauth2/user/OAuth2UserUnlinkManager.java, src/main/java/store/teabliss/common/security/utils/CookieUtils.java, src/main/resources/application.yml
- [v] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/ouath2 -> dev
- 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
- Init 기능으로 현재 프론트엔드분과 의논 후 진행 예정할것입니다.
- 테스트 프론트 페이지에서 정상적으로 Access, Refresh Token 값을 반환함을 확인.
=> [feat] OAuth2 구글 로그인 Init

src/main/java/store/teabliss/common/config/SecurityConfig.java, src/main/java/store/teabliss/common/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/store/teabliss/common/security/oauth2/service/CustomOAuth2UserService.java, src/main/java/store/teabliss/common/security/oauth2/service/OAuth2UserPrincipal.java, src/main/java/store/teabliss/common/security/oauth2/user/OAuth2Provider.java, src/main/java/store/teabliss/member/entity/Member.java, src/main/java/store/teabliss/member/entity/typehandler/MemberRoleTypeHandler.java, src/main/java/store/teabliss/member/entity/typehandler/OAuth2ProviderTypeHandler.java, src/main/resources/mapper/MemberMapper.xml
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/oauth2 -> dev
- 구글 소셜 로그인 시, 처음 접속일 경우 회원가입 처리.
- 이 후, 첫 방문자/고객인 경우 JWT 발급 처리.
- Member 테이블 변경 후 JWT 처리까지 확인.
- 이 후, 프론트 엔드와 얘기를 나눠봐야함.
=> [feat] OAuth2 구글 로그인 회원가입/로그인 처리 기능 추가

src/main/java/store/teabliss/common/security/signin/service/JwtService.java, src/main/java/store/teabliss/common/security/utils/CookieUtils.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/member -> dev
- SameSite 오류로 인한 None 설정 추가.
- 정상적으로 발급된 쿠키에 SameSite="None"이 들어감을 확인.
=> [fix] SameSite None 설정 추가

src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/resources/mapper/TeaMapper.xml
- [✅] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
버그 수정입니다!
=> 🐛fix:데이터베이스 버그수정

src/main/resources/mapper/TeaMapper.xml
- [] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [✅] 버그 수정
ex) dev->main
=> 🐛fix:버그수정 !

src/main/java/store/teabliss/tea/controller/TeaController.java, src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/java/store/teabliss/tea/service/TeaService.java, src/main/resources/mapper/TeaMapper.xml
- [✅] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
전체 사이즈 조회 추가하였습니다!
=> ✨feat: 티 size 확인!

src/main/java/store/teabliss/ingredient/controller/IngredientController.java, src/main/java/store/teabliss/ingredient/dto/IngredientRequestDto.java, src/main/java/store/teabliss/ingredient/dto/IngredientResponse.java, src/main/java/store/teabliss/ingredient/dto/IngredientResponseDto.java, src/main/java/store/teabliss/ingredient/mapper/IngredientMapper.java, src/main/java/store/teabliss/ingredient/service/IngredientService.java, src/main/resources/mapper/IngredientMapper.xml
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/ingredient -> dev
- 재료 CRUD API 구성 완료.
- 정상 출력 확인.
=> [feat] 재료 API CRUD 기본 구성 완료

src/main/java/store/teabliss/ingredient/controller/IngredientController.java, src/main/java/store/teabliss/ingredient/dto/IngredientRequestDto.java, src/main/java/store/teabliss/ingredient/dto/IngredientResponseDto.java, src/main/java/store/teabliss/ingredient/entity/Ingredient.java, src/main/java/store/teabliss/ingredient/service/IngredientService.java, src/main/resources/mapper/IngredientMapper.xml
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/ingredient -> dev
- 재료 관련 [가격, 재고, 상태] 컬럼 추가로 인한 코드 수정.
- 재료  다중 업데이트 API 추가.
- 정상 확인 완료.
=> [feat] 재료 다중 Update API 추가 및 코드 수정

src/main/resources/mapper/IngredientMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 일부 쿼리 코드 수정
=> [fix] 재료 쿼리 코드 수정

src/main/java/store/teabliss/survey/controller/SurveyController.java, src/main/java/store/teabliss/survey/dto/SurveyCreateDto.java, src/main/java/store/teabliss/survey/dto/SurveyResponse.java, src/main/java/store/teabliss/survey/entity/Survey.java, src/main/java/store/teabliss/survey/mapper/SurveyMapper.java, src/main/java/store/teabliss/survey/service/SurveyService.java, src/main/resources/mapper/SurveyMapper.xml
- [v] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/survey -> dev
- 설문조사 추가 관련 API Init
- 현재 Security 에러로 인한 작업으로 이후 진행 작업.
=> [feat] 설문조사 코드 Init

src/main/java/store/teabliss/common/config/SwaggerConfig.java
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat_v2/security -> dev
- Https 리버스 프록시 추가로 인한 스웨거 수정.
- 설문조사 관련 스웨거 값 추가.
=> [fix] 스웨거 Https Cors 에러 수정, 설문조사 추가

src/main/java/store/teabliss/common/config/SecurityConfig.java, src/main/java/store/teabliss/common/security/signin/JwtAuthorizationFilter.java, src/main/java/store/teabliss/common/security/signin/service/JwtService.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat_v2/security-> dev
- 인증/인가 테스트 시 Access Token 헤더를 "Authorization"으로 변경.
- 인가 테스트 정상 후 인가 작업이 필요한 API 정상 출력 됨을 확인.
=> [fix] Spring Security 인증/인가 에러 수정

src/main/java/store/teabliss/survey/dto/SurveyCreateDto.java, src/main/resources/mapper/SurveyMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/survey -> dev
- 설문조사 등록 시 member의 id에 관련된 에러 수정.
- 로컬에서 자체 로그인/소셜 로그인으로 등록된 데이터 정상적으로 등록됨을 확인.
=> [fix] 설문조사 등록 에러 수정

src/main/java/store/teabliss/common/config/SecurityConfig.java, src/main/java/store/teabliss/common/security/signin/JwtAuthorizationFilter.java, src/main/java/store/teabliss/common/security/signin/service/JwtService.java, src/main/java/store/teabliss/survey/dto/SurveyCreateDto.java, src/main/resources/mapper/SurveyMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 설문조사, 시큐리티 인가 에러 수정 작업.
=> [fix] 에러 수정 작업 main PR

src/main/java/store/teabliss/common/config/SecurityConfig.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
=> [fix] 인증/인가 URL 변경

src/main/java/store/teabliss/basket/controller/BasketController.java, src/main/java/store/teabliss/basket/dto/BasketDto.java, src/main/java/store/teabliss/basket/dto/DeleteBasketDto.java, src/main/java/store/teabliss/basket/entity/Basket.java, src/main/java/store/teabliss/basket/mapper/BasketMapper.java, src/main/java/store/teabliss/basket/service/BasketService.java, src/main/java/store/teabliss/common/config/SwaggerConfig.java, src/main/java/store/teabliss/review/controller/ReviewController.java, src/main/java/store/teabliss/review/dto/ReviewDto.java, src/main/java/store/teabliss/review/entity/Review.java, src/main/java/store/teabliss/review/mapper/ReviewMapper.java, src/main/java/store/teabliss/review/service/ReviewService.java, src/main/java/store/teabliss/tea/controller/TeaController.java, src/main/java/store/teabliss/tea/dto/TeaFinalDto.java, src/main/java/store/teabliss/tea/dto/TeaSearchDto.java, src/main/java/store/teabliss/tea/entity/Tea.java, src/main/java/store/teabliss/tea/entity/TeaFlavor.java, src/main/java/store/teabliss/tea/entity/TeaIngredient.java, src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/java/store/teabliss/tea/service/TeaService.java, src/main/resources/mapper/BasketMapper.xml, src/main/resources/mapper/ReviewMapper.xml, src/main/resources/mapper/TeaMapper.xml
- [✅] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
대공사및 장바구니,전체리뷰 추가했습니다.
=> 완성차 대공사및 장바구니,전체리뷰 추가

src/main/java/store/teabliss/common/config/SecurityConfig.java, src/main/java/store/teabliss/tea/dto/TeaDto.java, src/main/java/store/teabliss/tea/dto/TeaFinalDto.java, src/main/java/store/teabliss/tea/entity/Tea.java, src/main/java/store/teabliss/tea/service/TeaService.java, src/main/resources/mapper/TeaMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/tea -> dev
- 쿼리문, 코드 이상한 부분 일부 수정(재호님과 다시 상의 예정).
- 시큐리티 설정으로 Get 관련 API는 비회원도 조회 가능하도록 설정.
- 정상적으로 Access Token이 필요한 Post API를 제외하고 전부 조회 가능.
=> [fix] 차 완제품 Get 조회 시큐리티 설정 수정, 차 완제품 코드 일부 수정

src/main/java/store/teabliss/common/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/dto/MemberEditDto.java, src/main/java/store/teabliss/member/entity/Member.java, src/main/java/store/teabliss/member/mapper/MemberMapper.java, src/main/java/store/teabliss/member/service/MemberService.java, src/main/resources/mapper/MemberMapper.xml
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/member-> dev
- 회원 정보/비밀번호 수정 코드 추가, 프로필 요청 및 회원 주소 요청 관련 Init
- 이전 업데이트에서 추가 작업으로 인해 로컬 확인 정상.
=> [feat] 마이페이지 관련 API 추가 및 해당 코드 수정

src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/dto/MemberDto.java, src/main/java/store/teabliss/member/dto/MemberEditDto.java, src/main/java/store/teabliss/member/dto/MemberPasswordDto.java, src/main/java/store/teabliss/member/mapper/MemberMapper.java, src/main/java/store/teabliss/member/service/MemberService.java, src/main/resources/mapper/MemberMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/member -> dev
- 회의 후, 회원 정보에 대한 변경작업
- 회원 정보 요청 ("/info")로 마이페이지에 필요한 값 전부 내보내기 작업.
- 회원정보 수정("/edit", 프로필과 닉네임), 비밀번호 수정("/password") 작업
- 확인을 하지 못하였으나 크게 변경된 점이 없음을 인지.
=> [fix] 마이페이지 API 명세 수정

src/main/java/store/teabliss/common/config/SecurityConfig.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/member -> dev
=> [fix] Spring Security 프론트 에러 수정2

src/main/java/store/teabliss/tea/mapper/TeaMapper.java
=> ♻refactor: mapper 핫픽스

src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/dto/MemberAddressDto.java, src/main/java/store/teabliss/member/exception/MemberExceptionHandler.java, src/main/java/store/teabliss/member/exception/MemberStatus.java, src/main/java/store/teabliss/member/exception/NotEqualPasswordException.java, src/main/java/store/teabliss/member/service/MemberService.java, src/main/resources/mapper/MemberMapper.xml
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/member -> dev
- 회원 정보(주소, 프로필 이미지) 수정 API 완료.
- 회원 비밀번호 수정 API 완료.
- 회원 주소 수정 API 완료.
- 해당 비밀번호 관련된 커스텀 에러 핸들러 추가.
- Local 스웨거로 정상 작동 하는 것을 확인 .
=> [fix] 회원 정보/비밀번호/주소 변경 API 추가 및 수정 완료

src/main/java/store/teabliss/common/config/SecurityConfig.java, src/main/java/store/teabliss/common/dto/SearchDto.java, src/main/java/store/teabliss/review/controller/ReviewController.java, src/main/java/store/teabliss/review/dto/ReviewDto.java, src/main/java/store/teabliss/review/dto/ReviewResponse.java, src/main/java/store/teabliss/review/entity/Review.java, src/main/java/store/teabliss/review/mapper/ReviewMapper.java, src/main/java/store/teabliss/review/service/ReviewService.java, src/main/resources/mapper/ReviewMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/review -> dev
- mem_id(회원 아이디), tea_id(완제품 아이디) 컬럼 추가.
- like 컬럼 명칭 -> likes로 변경.
- createad 컬럼 명칭 -> create_dt로 변경.
- update_dt 컬럼 추가.
- 쿼리에 LIMIT 페이징 처리.
- page, limit를 동적 쿼리로 변경하여 작업 진행 중.
- isLastPage 임의 설정.
- 모든 리뷰 조회 컬럼 정상 작동.
- isLastPage가 lastPage로 출력되어 확인 중.
=> [fix] 리뷰 코드 전면 수정

src/main/java/store/teabliss/review/controller/ReviewController.java, src/main/java/store/teabliss/review/dto/ReviewCreateDto.java, src/main/java/store/teabliss/review/dto/ReviewDto.java, src/main/java/store/teabliss/review/dto/ReviewResponse.java, src/main/java/store/teabliss/review/dto/ReviewUpdateDto.java, src/main/java/store/teabliss/review/mapper/ReviewMapper.java, src/main/java/store/teabliss/review/service/ReviewService.java, src/main/resources/mapper/ReviewMapper.xml
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/review -> dev
- 리뷰 등록/수정 API 추가
- 마이 리뷰 리스트 API 추가
- Response 타입 변경 및 total(전체 개수) 추가
- 정상적으로 확인.
=> [feat] 리뷰 등록/수정 API 추가 및 Response 변경으로 인한 코드 수정

src/main/resources/application.yml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- google redirect-uri 기본 설정에서 https로 변경 작업.
- PR 후 확인해야함.
=> [fix] Security 수정

src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/dto/MemberDto.java, src/main/java/store/teabliss/member/dto/MemberResponse.java, src/main/java/store/teabliss/member/entity/Member.java, src/main/java/store/teabliss/member/mapper/MemberMapper.java, src/main/java/store/teabliss/member/service/MemberService.java, src/main/resources/mapper/MemberMapper.xml, src/main/resources/mapper/ReviewMapper.xml
- [v] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
ex) feat/admin -> dev
- 관리자 페이지, 회원 목록 조회 API 추가
- DB 로컬에서 테스트 정상.
=> [feat] 관리자 페이지 회원목록 조회 API 추가

src/main/java/store/teabliss/tea/dto/TeaFinalDto.java
=> fix:hot fix id dto 추가

src/main/resources/mapper/TeaMapper.xml
- [] 기능 추가
- [✅] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
수정 로직 버그 수정해서 다시 메인에 올립니다!
=> 🐛fix:수정 로직 버그 수정

src/main/java/store/teabliss/common/config/SwaggerConfig.java, src/main/java/store/teabliss/member/controller/AdminController.java, src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/service/MemberService.java
- [v] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/admin -> dev
- 관리자 회원 관련 API 분리를 위해 컨트롤러 단을 분리 처리.
=> [feat] 관리자의 회원 관련 API 컨트롤러단 분리, Swagger 추가

src/main/java/store/teabliss/ingredient/controller/IngredientController.java, src/main/java/store/teabliss/ingredient/dto/IngredientResponse.java, src/main/java/store/teabliss/ingredient/entity/Ingredient.java, src/main/java/store/teabliss/ingredient/mapper/IngredientMapper.java, src/main/java/store/teabliss/ingredient/service/IngredientService.java, src/main/java/store/teabliss/member/service/MemberService.java, src/main/resources/mapper/IngredientMapper.xml
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/admin -> dev
- 관리자 재료 단일 검색 추가.
- 재료 페이지네이션 변경으로 인한 코드 수정 작업.
=> [fix] 관리자 페이지 재료 관련 API 단일 검색 추가 및 코드 수정

src/main/java/store/teabliss/common/config/SwaggerConfig.java, src/main/java/store/teabliss/ingredient/controller/IngredientController.java, src/main/java/store/teabliss/ingredient/dto/IngredientResponse.java, src/main/java/store/teabliss/ingredient/entity/Ingredient.java, src/main/java/store/teabliss/ingredient/mapper/IngredientMapper.java, src/main/java/store/teabliss/ingredient/service/IngredientService.java, src/main/java/store/teabliss/member/controller/AdminController.java, src/main/java/store/teabliss/member/controller/MemberController.java, src/main/java/store/teabliss/member/service/MemberService.java, src/main/java/store/teabliss/review/controller/ReviewController.java, src/main/resources/mapper/IngredientMapper.xml, src/main/resources/mapper/TeaMapper.xml
- [v] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
=> [feat, fix] 관리자 화면 Main PR

src/main/java/store/teabliss/basket/controller/BasketController.java, src/main/java/store/teabliss/basket/dto/BasketDto.java, src/main/java/store/teabliss/basket/dto/DeleteBasketDto.java, src/main/java/store/teabliss/basket/entity/Basket.java, src/main/java/store/teabliss/basket/mapper/BasketMapper.java, src/main/java/store/teabliss/basket/service/BasketService.java, src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/resources/mapper/BasketMapper.xml
- [] 기능 추가
- [✅] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
basket userid 대입시 수정입니다!
=> ♻refactor: basket userid 대입 시 수정

src/main/java/store/teabliss/basket/controller/BasketController.java, src/main/java/store/teabliss/basket/dto/BasketDto.java, src/main/java/store/teabliss/basket/entity/Basket.java, src/main/java/store/teabliss/basket/mapper/BasketMapper.java, src/main/java/store/teabliss/basket/service/BasketService.java, src/main/java/store/teabliss/tea/controller/TeaController.java, src/main/java/store/teabliss/tea/dto/TeaPatchDto.java, src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/java/store/teabliss/tea/service/TeaService.java, src/main/resources/mapper/BasketMapper.xml, src/main/resources/mapper/TeaMapper.xml
- [] 기능 추가
- [✅] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
장바구니 및 tea 전반적인 수정 입니다!
=> 장바구니및 tea 전반적인 수정

src/main/java/store/teabliss/basket/dto/BasketDto.java, src/main/java/store/teabliss/tea/controller/TeaController.java, src/main/java/store/teabliss/tea/dto/TeaDto.java, src/main/java/store/teabliss/tea/dto/TeaPatchDto.java, src/main/java/store/teabliss/tea/entity/TeaFlavor.java, src/main/java/store/teabliss/tea/entity/TeaIngredient.java, src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/java/store/teabliss/tea/service/TeaService.java, src/main/resources/mapper/TeaMapper.xml
- [] 기능 추가
- [✅] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
완성차 수정 안되는 로직 수정하였습니다.
=> 완성차 수정안되는 로직 수정

src/main/resources/mapper/BasketMapper.xml
- [] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [✅] 버그 수정
dev->main
=> fix basketmapper수정

src/main/java/store/teabliss/basket/controller/BasketController.java, src/main/java/store/teabliss/basket/dto/DeleteBasketDto.java, src/main/java/store/teabliss/basket/mapper/BasketMapper.java, src/main/java/store/teabliss/basket/service/BasketService.java, src/main/resources/mapper/BasketMapper.xml
- [] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [✅] 버그 수정
dev->main
다시 한번 철저히 장바구니 api 설정 하고 테스트 완료하였습니다
=> 전반적인 basket 장바구니 api 수정

src/main/java/store/teabliss/ingredient/controller/IngredientController.java, src/main/java/store/teabliss/ingredient/dto/IngredientCreateDto.java, src/main/java/store/teabliss/ingredient/service/IngredientService.java, src/main/resources/mapper/IngredientMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 쿼리 에러 수정.
- 재료 Create 일부 수정.
- 정상 작동
=> [fix] 재료 쿼리 에러 수정

src/main/java/store/teabliss/survey/controller/SurveyController.java, src/main/java/store/teabliss/survey/dto/SurveyCreateDto.java, src/main/java/store/teabliss/survey/dto/SurveyDto.java, src/main/java/store/teabliss/survey/dto/SurveyResponse.java, src/main/java/store/teabliss/survey/entity/Survey.java, src/main/java/store/teabliss/survey/mapper/SurveyMapper.java, src/main/java/store/teabliss/survey/service/SurveyService.java, src/main/java/store/teabliss/tea/dto/TeaFinalDto.java, src/main/java/store/teabliss/tea/entity/Tea.java, src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/resources/mapper/SurveyMapper.xml, src/main/resources/mapper/TeaMapper.xml
- [v] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/survey-> dev
- 설문조사 Get API 추가.
- 해당 설문조사에 따른 완제품 랜덤 3개 출력하는 쿼리문 추가.
- 로컬에서 테스트 정상적으로 출력.
=> [feat] 설문조사 Get API 추가

src/main/java/store/teabliss/review/dto/ReviewCreateDto.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 리뷰 등록 시 별점(좋아요?) 추가.
=> [fix] 리뷰 등록 별점 추가

src/main/java/store/teabliss/review/dto/ReviewDto.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- like -> likes 로 변경
=> [fix] Review Dto 수정

src/main/java/store/teabliss/review/controller/ReviewController.java, src/main/java/store/teabliss/review/mapper/ReviewMapper.java, src/main/java/store/teabliss/review/service/ReviewService.java, src/main/resources/mapper/IngredientMapper.xml, src/main/resources/mapper/ReviewMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 민보님이 요청하신 Review Top 관련 Limit 에러 수정.
- 찬용님이 요청하신 재료 Insert 에러 수정
- 로컬에서 전부 정상적으로 테스트 완료.
=> [fix] 리뷰 Top Limit 에러, 재료 Insert 에러 문의 수정

src/main/java/store/teabliss/review/dto/ReviewCreateDto.java, src/main/java/store/teabliss/review/dto/ReviewDto.java, src/main/java/store/teabliss/review/dto/ReviewUpdateDto.java, src/main/java/store/teabliss/review/entity/Review.java, src/main/java/store/teabliss/review/service/ReviewService.java, src/main/java/store/teabliss/tea/controller/TeaController.java, src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/java/store/teabliss/tea/service/TeaService.java, src/main/resources/mapper/IngredientMapper.xml, src/main/resources/mapper/TeaMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 민보님 요청으로 리뷰의 완제품 차 이미지 Response 출력.
- 찬용님 요청으로 재료 이미지 쿼리문 수정.
- 로컬 테스트 정상 완료.
=> [fix] 리뷰 Response 값 수정, 재료 쿼리문 수정 요청 완료

src/main/resources/mapper/ReviewMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 쿼리문의 id로 문자명을 변경하지 않음.
- 이를 수정 후 정상적으로 리뷰에 대한 id 정상 출력.
=> [fix] 리뷰 쿼리문 수정

src/main/java/store/teabliss/common/config/SecurityConfig.java, src/main/java/store/teabliss/member/controller/AdminController.java, src/main/java/store/teabliss/member/dto/MemberEditDto.java, src/main/resources/mapper/MemberMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- feat/admin -> dev
- 관리자 수정 요청으로 인한 코드 및 쿼리문 수정.
- 로컬에서 정상적으로 회원 수정 완료, 회원에 대한 조건문 설정 완료.
=> [fix] 관리자 수정 요청 및 쿼리 수정

build.gradle, src/main/java/store/teabliss/basket/mapper/BasketMapper.java, src/main/java/store/teabliss/payment/controller/PaymentController.java, src/main/java/store/teabliss/payment/dto/PaymentResponseDto.java, src/main/java/store/teabliss/payment/entity/DBAmount.java, src/main/java/store/teabliss/payment/entity/DBCard.java, src/main/java/store/teabliss/payment/entity/DBCustomer.java, src/main/java/store/teabliss/payment/entity/DBPayment.java, src/main/java/store/teabliss/payment/entity/DBProduct.java, src/main/java/store/teabliss/payment/entity/PayAmount.java, src/main/java/store/teabliss/payment/entity/PayCustomer.java, src/main/java/store/teabliss/payment/entity/PayMethod.java, src/main/java/store/teabliss/payment/entity/PayProduct.java, src/main/java/store/teabliss/payment/mapper/PaymentMapper.java, src/main/java/store/teabliss/payment/service/PaymentService.java, src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/resources/mapper/BasketMapper.xml, src/main/resources/mapper/PaymentMapper.xml, src/main/resources/mapper/TeaMapper.xml
- [✅] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
결제 기능 추가했습니다!
=> 결제 기능 추가! 

src/main/java/store/teabliss/member/dto/MemberDto.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- /admin/{id} 에 대한 Profile 컬럼 객체 추가.
=> [fix] Admin 관련 API 수정

src/main/java/store/teabliss/common/security/signin/RequestMatcherHolder.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 마이페이지 리뷰 관련 에러로 인한 Security Filter 제한 API 수정 작업.
=> [fix] Security Filter API 관련 수정

src/main/java/store/teabliss/common/security/signin/service/JwtService.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 민보님 요청으로 JWT 토큰 관련 경과 체크용 시간 변경 작업.
=> [fix] Access Token, Refresh Token 시간 변경

src/main/java/store/teabliss/common/security/signin/service/JwtService.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 민보님 요청으로 JWT 토큰 관련 경과 체크용 시간 변경 2번째 작업.
=> [fix] Access Token, Refresh Token 시간 변경 2

src/main/java/store/teabliss/common/security/signin/RequestMatcherHolder.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- 토큰 재발급 API 시큐리티 필터 미적용 작업.
=> [fix] Re-Issue 필터 적용 수정

src/main/java/store/teabliss/common/security/signin/service/JwtService.java
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- JWT 토큰 유지시간 정상화.
=> [fix] JWT 토큰 유지시간 정상화 처리

src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/java/store/teabliss/tea/service/TeaService.java
- [] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [✅] 버그 수정
=> fix:hot fix

src/main/resources/mapper/TeaMapper.xml
- [] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [✅] 버그 수정
dev->main
mapper 수정했습니다!
=> 🐛fix: mapper 수정

src/main/java/store/teabliss/payment/controller/PaymentController.java, src/main/java/store/teabliss/payment/dto/PaymentRequestDto.java, src/main/java/store/teabliss/payment/entity/DBPayment.java, src/main/java/store/teabliss/payment/entity/DBProduct.java, src/main/java/store/teabliss/payment/mapper/PaymentMapper.java, src/main/java/store/teabliss/payment/service/PaymentService.java, src/main/java/store/teabliss/review/mapper/ReviewMapper.java, src/main/java/store/teabliss/tea/mapper/TeaMapper.java, src/main/resources/application.yml, src/main/resources/mapper/PaymentMapper.xml, src/main/resources/mapper/ReviewMapper.xml, src/main/resources/mapper/TeaMapper.xml
- [✅] 기능 추가
- [] 기능 수정
- [] 기능 삭제
- [] 버그 수정
dev->main
결제 내역 조회 로직 추가
=> 결제 내역 조회 로직 추가!

src/main/java/store/teabliss/ingredient/service/IngredientService.java, src/main/java/store/teabliss/survey/entity/Survey.java, src/main/java/store/teabliss/survey/service/SurveyService.java, src/main/resources/mapper/SurveyMapper.xml
- [] 기능 추가
- [v] 기능 수정
- [] 기능 삭제
- [] 버그 수정
- dev -> main
- insert 시 id 반환 에러인 부분 수정
- 로컬에서 정상적으로 반환인 것을 확인.
=> [fix] Post시 id 넘기기 적용 안되있는 부분 수정
